spring.application.name=FizzBuzz

# DataSource 
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.encoding=UTF-8
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=optional:classpath:data.sql
spring.h2.console.path=/h2-console
spring.datasource.generate-unique-name=false

#H2DB
spring.h2.console.enabled=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

#MyBatis
mybatis.mapper-locations=classpath*:/mapper/h2/*.xml
mybatis.configuration.map-underscore-to-camel-case=true 
mybatis.type-aliases-package=com.example.domain.user.model

#message
spring.messages.basename=i18n/messages,i18n/ValidationMessages